apiVersion: v1
kind: Service
metadata:
  name: anonymbe-mem-service
  labels:
    name: anonymbe-mem
spec:
  type: NodePort
  ports:
  - port: 4444
    targetPort: 4444
    nodePort: 30445
  selector:
    role: anonymbe-mem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anonymbe-mem
spec:
  selector:
    matchLabels:
      role: anonymbe-mem
  replicas: 1
  template:
    metadata:
      labels:
        role: anonymbe-mem
    spec:
      terminationGracePeriodSeconds: 10
      imagePullSecrets:
      - name: regcred
      containers:
      - name: anonymbe-mem-container
        image: sebvaucher/anonymbe:0.17-mem
        args:
        - "./bin/anonymbe"
        stdin: true
        tty: true
        ports:
        - name: service-port
          containerPort: 4444
        resources:
          requests:
            intel.com/sgx: 5000
          limits:
            intel.com/sgx: 5000
        readinessProbe:
          httpGet:
            path: /ping
            port: service-port
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /ping
            port: service-port
            scheme: HTTPS
          initialDelaySeconds: 20
          periodSeconds: 10
