apiVersion: v1
kind: Service
metadata:
  name: anonymbe-service
  labels:
    name: anonymbe
spec:
  type: NodePort
  ports:
  - port: 4444
    targetPort: 4444
    nodePort: 30444
  selector:
    role: anonymbe
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anonymbe
spec:
  selector:
    matchLabels:
      role: anonymbe
  replicas: 1
  template:
    metadata:
      labels:
        role: anonymbe
    spec:
      terminationGracePeriodSeconds: 10
      imagePullSecrets:
      - name: regcred
      containers:
      - name: anonymbe-container
        image: sebvaucher/anonymbe:0.17
        args:
        - "./bin/anonymbe"
        - "-m"
        - "mongodb://mongod-0.mongodb-service.default.svc.cluster.local:27017,mongod-1.mongodb-service.default.svc.cluster.local:27017,mongod-2.mongodb-service.default.svc.cluster.local:27017/?replicaSet=rs0&ssl=true&sslAllowInvalidCertificates=true&sslAllowInvalidHostnames=true"
        stdin: true
        tty: true
        ports:
        - name: service-port
          containerPort: 4444
        resources:
          requests:
            intel.com/sgx: 5000
          limits:
            intel.com/sgx: 5000
        readinessProbe:
          httpGet:
            path: /ping
            port: service-port
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /ping
            port: service-port
            scheme: HTTPS
          initialDelaySeconds: 20
          periodSeconds: 10
