apiVersion: v1
kind: Service
metadata:
  name: writerproxy-token-service
  labels:
    name: writerproxy-token
spec:
  type: NodePort
  ports:
  - port: 4445
    targetPort: 4445
    nodePort: 30556
  selector:
    role: writerproxy-token
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: writerproxy-token
spec:
  selector:
    matchLabels:
      role: writerproxy-token
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        role: writerproxy-token
    spec:
      terminationGracePeriodSeconds: 10
      imagePullSecrets:
      - name: regcred
      containers:
      - name: writerproxy-container
        image: sebvaucher/anonymbe:0.32-writerproxy
        args:
        - "./bin/writeproxy"
        - "-m"
        - "minio-service.default.svc.cluster.local:9000"
        - "-a"
        - "access"
        - "-k"
        - "secretkey"
        - "-t"
        - "hoernli-5.maas:9443"
        - "-u"
        - x7nfS68A88FZ4yWOkL7pSJ7yvkIa
        - "-w"
        - Nu_yQoDYGiLVxBRAZTSg2hjwX9sa
        stdin: true
        tty: true
        ports:
        - name: service-port
          containerPort: 4445
        resources:
          requests:
            intel.com/sgx: 1
          limits:
            intel.com/sgx: 1
        readinessProbe:
          httpGet:
            path: /ping
            port: service-port
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /ping
            port: service-port
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 5

