apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    worker_processes 10;
    user nobody nobody;
    events {
        worker_connections 64;
    }
    stream {
        server {
            listen 7070;
            proxy_pass minio-service.default.svc.cluster.local:9000;
        }
    }
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        # Force scheduling on one particular node
        kubernetes.io/hostname: eiger-8
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      containers:
      - name: nginx
        image: nginx:1.14.2-alpine
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        ports:
        - containerPort: 7070
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  ports:
    - port: 7070
      targetPort: 7070
      nodePort: 30700
      protocol: TCP
  selector:
    app: nginx
